long dvk_vcopy(int src_ep, void *src_addr, int dst_ep, void *dst_addr, int bytes);
long dvk_dvs_end(void);
long dvk_dc_init(dc_usr_t *dcu_ptr);
long dvk_dc_end(int dcid);
long dvk_getep(int pid);
long dvk_getdvsinfo(dvs_usr_t *dvsu_ptr);
long dvk_proxies_unbind(int pxid);
long dvk_node_down(int nodeid);
long dvk_rcvrqst_T(message *mptr, long timeout);
long dvk_getdcinfo(int dcid, dc_usr_t *dcu_ptr);
long dvk_getnodeinfo(int nodeid, node_usr_t *node_ptr);
long dvk_relay(int endpoint, message *mptr);
long dvk_wakeup(int dcid, int dst_ep);
long dvk_put2lcl(cmd_t *header, proxy_payload_t *payload);
long dvk_add_node(int dcid, int nodeid);
long dvk_del_node(int dcid, int nodeid);
long dvk_dvs_init(int nodeid, dvs_usr_t *dvsu_ptr);
long dvk_proxy_conn(int pxid, int status);
long dvk_wait4bindep_X(int cmd, int endpoint, unsigned long timeout);
long dvk_unbind_T(int dcid, int endpoint, unsigned long timeout);
long dvk_send_T(int endpoint , message *mptr, long timeout);
long dvk_receive_T(int endpoint , message *mptr, long timeout);
long dvk_sendrec_T(int endpoint , message *mptr, long timeout);
long dvk_reply_T(int endpoint , message *mptr, long timeout);
long dvk_notify_X(int nr , int endpoint, int value);
long dvk_setpriv(int dcid , int endpoint, priv_usr_t *priv);
long dvk_getpriv(int dcid , int endpoint, priv_usr_t *priv);
long dvk_get2rmt_T(cmd_t *header, proxy_payload_t *payload , long timeout);
long dvk_node_up(char *name, int nodeid,  int pxid);
long dvk_getproxyinfo(int pxid, proc_usr_t *sproc_usr, proc_usr_t *rproc_usr);
long dvk_getprocinfo(int dcid, int p_nr, proc_usr_t *p_usr);
long dvk_bind_X(int cmd, int dcid, int pid, int endpoint, int nodeid);
long dvk_proxies_bind(char *name, int pxid, int spid, int rpid, int maxcopybuf);
long dvk_migrate_X(int cmd, int pid, int dcid, int endpoint, int nodeid);
